// Code generated by protoc-gen-go. DO NOT EDIT.
// source: movie.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetMovieRequest struct {
	MovieId              int64    `protobuf:"varint,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMovieRequest) Reset()         { *m = GetMovieRequest{} }
func (m *GetMovieRequest) String() string { return proto.CompactTextString(m) }
func (*GetMovieRequest) ProtoMessage()    {}
func (*GetMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{0}
}

func (m *GetMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieRequest.Unmarshal(m, b)
}
func (m *GetMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieRequest.Marshal(b, m, deterministic)
}
func (m *GetMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieRequest.Merge(m, src)
}
func (m *GetMovieRequest) XXX_Size() int {
	return xxx_messageInfo_GetMovieRequest.Size(m)
}
func (m *GetMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieRequest proto.InternalMessageInfo

func (m *GetMovieRequest) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

type GetMovieResponse struct {
	MovieId              int64    `protobuf:"varint,1,opt,name=movie_id,json=movieId,proto3" json:"movie_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Poster               string   `protobuf:"bytes,3,opt,name=poster,proto3" json:"poster,omitempty"`
	Url                  string   `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMovieResponse) Reset()         { *m = GetMovieResponse{} }
func (m *GetMovieResponse) String() string { return proto.CompactTextString(m) }
func (*GetMovieResponse) ProtoMessage()    {}
func (*GetMovieResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{1}
}

func (m *GetMovieResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieResponse.Unmarshal(m, b)
}
func (m *GetMovieResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieResponse.Marshal(b, m, deterministic)
}
func (m *GetMovieResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieResponse.Merge(m, src)
}
func (m *GetMovieResponse) XXX_Size() int {
	return xxx_messageInfo_GetMovieResponse.Size(m)
}
func (m *GetMovieResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieResponse proto.InternalMessageInfo

func (m *GetMovieResponse) GetMovieId() int64 {
	if m != nil {
		return m.MovieId
	}
	return 0
}

func (m *GetMovieResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetMovieResponse) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

func (m *GetMovieResponse) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*GetMovieRequest)(nil), "main.GetMovieRequest")
	proto.RegisterType((*GetMovieResponse)(nil), "main.GetMovieResponse")
}

func init() { proto.RegisterFile("movie.proto", fileDescriptor_fde087a4194eda75) }

var fileDescriptor_fde087a4194eda75 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcd, 0x2f, 0xcb,
	0x4c, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xd2, 0xe1,
	0xe2, 0x77, 0x4f, 0x2d, 0xf1, 0x05, 0x89, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x49,
	0x72, 0x71, 0x80, 0xd5, 0xc5, 0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0xb1, 0x83,
	0xf9, 0x9e, 0x29, 0x4a, 0xd9, 0x5c, 0x02, 0x08, 0xd5, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x78,
	0x94, 0x0b, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06,
	0x81, 0xd9, 0x42, 0x62, 0x5c, 0x6c, 0x05, 0xf9, 0xc5, 0x25, 0xa9, 0x45, 0x12, 0xcc, 0x60, 0x51,
	0x28, 0x4f, 0x48, 0x80, 0x8b, 0xb9, 0xb4, 0x28, 0x47, 0x82, 0x05, 0x2c, 0x08, 0x62, 0x1a, 0xb9,
	0x70, 0xb1, 0x82, 0x6d, 0x12, 0xb2, 0xe6, 0xe2, 0x80, 0xd9, 0x2a, 0x24, 0xaa, 0x07, 0x72, 0xb6,
	0x1e, 0x9a, 0x9b, 0xa5, 0xc4, 0xd0, 0x85, 0x21, 0x8e, 0x53, 0x62, 0x48, 0x62, 0x03, 0xfb, 0xd6,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x89, 0x02, 0x3e, 0xe2, 0xfc, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MovieClient is the client API for Movie service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MovieClient interface {
	GetMovie(ctx context.Context, in *GetMovieRequest, opts ...grpc.CallOption) (*GetMovieResponse, error)
}

type movieClient struct {
	cc *grpc.ClientConn
}

func NewMovieClient(cc *grpc.ClientConn) MovieClient {
	return &movieClient{cc}
}

func (c *movieClient) GetMovie(ctx context.Context, in *GetMovieRequest, opts ...grpc.CallOption) (*GetMovieResponse, error) {
	out := new(GetMovieResponse)
	err := c.cc.Invoke(ctx, "/main.Movie/GetMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieServer is the server API for Movie service.
type MovieServer interface {
	GetMovie(context.Context, *GetMovieRequest) (*GetMovieResponse, error)
}

// UnimplementedMovieServer can be embedded to have forward compatible implementations.
type UnimplementedMovieServer struct {
}

func (*UnimplementedMovieServer) GetMovie(ctx context.Context, req *GetMovieRequest) (*GetMovieResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovie not implemented")
}

func RegisterMovieServer(s *grpc.Server, srv MovieServer) {
	s.RegisterService(&_Movie_serviceDesc, srv)
}

func _Movie_GetMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMovieRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServer).GetMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Movie/GetMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServer).GetMovie(ctx, req.(*GetMovieRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Movie_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.Movie",
	HandlerType: (*MovieServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovie",
			Handler:    _Movie_GetMovie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movie.proto",
}
